### ISSUE TITLE
Previews failing for some pages

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-wordpress#120]
We often get preview failures for https://owid.cloud/admin/posts/preview/30223

```
FetchError: invalid json response body at https://owid.cloud/wp-json/wp/v2/pages/30223/revisions reason: Unexpected token < in JSON at position 0
```

I quickly checked the Wordpress error logs:

```
Notice: Undefined index: mediaId in /home/owid/live-wordpress/web/app/plugins/owid/src/ProminentLink/prominent-link.php on line 26
Notice: Undefined index: mediaId in /home/owid/live-wordpress/web/app/plugins/owid/src/ProminentLink/prominent-link.php on line 26
[{"author":2,"date":"2020-07-14T12:56:15","date_gmt":"2020-07-14T11:56:15","id":34965,"modified":"2020-07-14T12:56:15","modified_gmt":"2020-07-14T11:56:15","parent":30223,"slug":"30223-revision-v1","guid":{"rendered":"https:\/\/owid.cloud\/30223-revision-v1"},"title":{"rendered":"Coronavirus Pandemic (COVID-19)"},"content":{"rendered":"\n\n\n\n\n
```

I am a total noob at PHP so haven't tried to fix it, but it seems that possibly `mediaId` is missing despite `mediaUrl` being present in the prominent link code? The error happens on line 26:

https://github.com/owid/owid-wordpress/blob/92547f6f686a63c677a0026e3d424ede890e45a8/web/app/plugins/owid/src/ProminentLink/prominent-link.php#L25-L29

**Comment by mlbrgl** [comment]
@danielgavrilov thanks for the report!

Fixed here: https://github.com/owid/owid-grapher/commit/e1662536583a724a4892d897095cea167d9be425 (PHP timing out trying to render an unnecessary large number of revisions)

I'll keep an eye on the discrepancy between `mediaId` and `mediaUrl`, it looks like it was broken in an old revision only (for that post at least).
